executor: go
environment:
  GO_TAGS: "ui codegen_generated"
steps:
  - checkout
  - run: apt-get update; apt-get install -y sudo unzip zip
  - run: make deps
  - install-protoc
  - run: ./scripts/vagrant-linux-unpriv-ui.sh
  - run: sudo -E PATH="$GOPATH/bin:/usr/local/go/bin:$PATH" make prerelease
  - run: make pkg/windows_amd64.zip pkg/linux_amd64.zip
  - store_artifacts:
      path: pkg/windows_amd64.zip
      destination: /builds/nomad_windows_amd64.zip
  - store_artifacts:
      path: pkg/linux_amd64.zip
      destination: /builds/nomad_linux_amd64.zip
