name: install-golang
inputs:
  target_directory:
    required: false
    default: "/usr/local"
runs:
  using: composite
  steps:
  - name: Install golang
    run: |-
      set -x

      echo installing golang ${GO_VERSION}

      case "${OSTYPE}" in
        linux*)  os="linux" ;;
        darwin*) os="darwin" ;;
        msys*)   os="windows" ;;
        *)       echo "unknown os: ${OSTYPE}"; exit 1 ;;
      esac

      if [[ "${os}" != "windows" ]]
      then
        sudo rm -rf ${{ inputs.target_directory }}/go
        sudo mkdir -p ${{ inputs.target_directory }}
        curl -SL --fail -o /tmp/golang.tar.gz https://dl.google.com/go/go${GOLANG_VERSION}.${os}-amd64.tar.gz
        sudo tar -C ${{ inputs.target_directory }} -xzf /tmp/golang.tar.gz
        rm -rf /tmp/golang.tar.gz
      else
        rm -rf ${{ inputs.target_directory }}/go
        mkdir -p ${{ inputs.target_directory }}
        curl -SL --fail -o /tmp/go.zip https://dl.google.com/go/go${GOLANG_VERSION}.windows-amd64.zip
        unzip -q -o /tmp/go.zip -d ${{ inputs.target_directory }}
        rm -rf /tmp/go.zip
      fi
    shell: bash