name: generate-static-assets

on:
  push:
    branches:
      - test-generate-static-assets

jobs:
  generate-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate static assets
        id: generate-static-assets
        run: make static-assets
      - name: Commit and push changes
        id: commit-change-push
        run: |
          echo "committing generated files"
          git add -A .
          find . -name '*.generated.go' -not -path './vendor/*' -exec git add -f '{}' \;
          if ! git diff-index --quiet HEAD --; \
          then \
            git commit --message "Generate files for $(NOMAD_VERSION) release"; \
            git push origin "$(git rev-parse --abbrev-ref HEAD)" \
          else \
            echo "no files were updated" \
          fi
