name: Semgrep

on:
  pull_request: {}
  # Skipping push for now since it would run against the entire code base.
  # push:

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_SEND_METRICS: 0
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: returntocorp/semgrep-action@v1
