name: Core CI Tests
on:
  push:
    branches-ignore:
      - main
      - release-**
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.changelog/**'
      - '.tours/**'
      - 'contributing/**'
      - 'demo/**'
      - 'dev/**'
      - 'e2e/terraform/**'
      - 'e2e/ui/**'
      - 'integrations/**'
      - 'pkg/**'
      - 'scripts/**'
      - 'terraform/**'
      - 'ui/**'
      - 'website/**'
env:
  VERBOSE: 1
  GO_VERSION: 1.19.1
  GOTESTARCH: amd64
  CONSUL_VERSION: 1.12.6
  VAULT_VERSION: 1.12.0
  NOMAD_SLOW_TEST: 0
  NOMAD_TEST_LOG_LEVEL: OFF
jobs:
  mods:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/setup-golang
        with:
          cache-key: core
      - name: Setup Go modules
        run: |
          make tidy
          make bootstrap
